npx nest g module auth --no-spec
npx nest g service auth --no-spec
npx nest g controller auth --no-spec
npx nest g module users --no-spec
npx nest g service users --no-spec
npx nest g controller users --no-spec
npx nest g module organizations --no-spec
npx nest g service organizations --no-spec
npx nest g controller organizations --no-spec
npx nest g module polls --no-spec
npx nest g service polls --no-spec
npx nest g controller polls --no-spec
npx nest g module votes --no-spec
npx nest g service votes --no-spec
npx nest g controller votes --no-spec
npx nest g module superadmin --no-spec
npx nest g service superadmin --no-spec
npx nest g controller superadmin --no-spec
